"""Configurable file filter for repository scanning."""

from pathlib import Path

from app.core.security import is_binary_extension


class FileFilter:
    """Filters files and directories during repository scanning.
    
    All filter lists are configurable — override at construction time
    or modify the class attributes for global changes.
    """

    IGNORED_DIRECTORIES = {
        # Version control
        ".git",
        ".svn",
        ".hg",
        # Dependencies
        "node_modules",
        "bower_components",
        "jspm_packages",
        "vendor",
        # Python
        "venv",
        ".venv",
        "env",
        ".env",
        "__pycache__",
        ".eggs",
        "*.egg-info",
        ".mypy_cache",
        ".pytest_cache",
        ".ruff_cache",
        ".tox",
        # Build output
        "dist",
        "build",
        "out",
        "target",
        "bin",
        "obj",
        # Coverage/test artifacts
        "coverage",
        "htmlcov",
        ".nyc_output",
        # Framework specific
        ".next",
        ".nuxt",
        ".svelte-kit",
        ".cache",
        ".parcel-cache",
        # IDE
        ".idea",
        ".vscode",
        ".vs",
    }

    def __init__(
        self,
        ignored_dirs: set[str] | None = None,
        ignored_extensions: set[str] | None = None,
    ):
        if ignored_dirs is not None:
            self.ignored_dirs = ignored_dirs
        else:
            self.ignored_dirs = self.IGNORED_DIRECTORIES

        self.ignored_extensions = ignored_extensions  # If None, use security module

    def should_ignore_directory(self, name: str) -> bool:
        """Check if a directory should be skipped during scanning."""
        return name in self.ignored_dirs

    def should_ignore_file(self, path: Path, max_size: int) -> bool:
        """Check if a file should be skipped during scanning."""
        try:
            if path.stat().st_size > max_size:
                return True
        except OSError:
            return True

        if is_binary_extension(path.suffix):
            return True

        if path.is_symlink():
            return True

        return False

    def is_minified(self, path: Path) -> bool:
        """Heuristic: detect minified JS/CSS files by average line length."""
        if path.suffix not in {".js", ".css"}:
            return False
        # Also check for .min. in the name
        if ".min." in path.name:
            return True
        try:
            with open(path, "r", encoding="utf-8", errors="replace") as f:
                lines = f.readlines()
                if not lines:
                    return False
                avg_len = sum(len(line) for line in lines) / len(lines)
                return avg_len > 200
        except Exception:
            return True

    def is_generated(self, path: Path) -> bool:
        """Heuristic: detect generated files by header comments."""
        try:
            with open(path, "r", encoding="utf-8", errors="replace") as f:
                for _ in range(5):
                    line = f.readline().lower()
                    if not line:
                        break
                    if any(marker in line for marker in [
                        "generated by",
                        "auto-generated",
                        "do not edit",
                        "do not modify",
                        "this file is generated",
                        "automatically generated",
                    ]):
                        return True
            return False
        except Exception:
            return False
